version: '3.9'

services:
  api:
    build:
      context: ./api
    command: daphne -b 0.0.0.0 -p 8000 simpleproxies_api.asgi:application
    secrets:
      - aws_ses_key
      - aws_ses_password
      - db_logger_name
      - db_logger_user
      - db_logger_password
      - db_logger_host
      - db_logger_port
      - django_secret_key
      - django_superuser_name
      - django_superuser_email
      - django_superuser_password
      - redis_password
    env_file:
      - api.env
    environment:
      DB_LOGGER_NAME: /run/secrets/db_logger_name
      DB_LOGGER_USER: /run/secrets/db_logger_user
      DB_LOGGER_PASSWORD: /run/secrets/db_logger_password
      DB_LOGGER_HOST: /run/secrets/db_logger_host
      DB_LOGGER_PORT: /run/secrets/db_logger_port
      DJANGO_SUPERUSER_NAME: /run/secrets/django_superuser_name
      DJANGO_SUPERUSER_EMAIL: /run/secrets/django_superuser_email
      DJANGO_SUPERUSER_PASSWORD: /run/secrets/django_superuser_password
      EMAIL_HOST_USER: /run/secrets/aws_ses_key
      EMAIL_HOST_PASSWORD: /run/secrets/aws_ses_password
      REDIS_PASSWORD: /run/secrets/redis_password
      SECRET_KEY: /run/secrets/django_secret_key
    ports:
      - 8000:8000
    volumes:
      - ./api/static/:/api/static/:rw
    depends_on:
      - db_logger
      - redis
  frontend:
    build:
      context: ./frontend
    user: nextjs
    command: npm run start
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
      NODE_ENV: production
  db_logger:
    image: postgres
    secrets:
      - db_logger_name
      - db_logger_user
      - db_logger_password
    environment:
      POSTGRES_DB_FILE: /run/secrets/db_logger_name
      POSTGRES_USER_FILE: /run/secrets/db_logger_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_logger_password
    ports:
      - 5432:5432
    volumes:
      - ./db_logger/var/lib/postgresql/data:/var/lib/postgresql/data:rw
  redis:
    image: redis:alpine
    restart: always
    secrets:
      - redis_password
    command: sh -c "cat /run/secrets/redis_password | xargs -0 redis-server --appendonly yes --requirepass"
    ports:
      - 6379:6379
    volumes:
      - /data
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/etc/nginx/proxy_params:/etc/nginx/proxy_params:ro
      - ./certbot/var/www/certbot/:/var/www/certbot/:ro
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./api/static/:/var/www/api/static/:ro
    depends_on:
      - api
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/var/www/certbot/:/var/www/certbot/:rw
      - ./certbot/etc/letsencrypt/:/etc/letsencrypt/:rw
      - ./certbot/var/log/letsencrypt/:/var/log/letsencrypt/:rw
secrets:
    aws_ses_key:
      file: ./secrets/aws_ses_key.txt
    aws_ses_password:
      file: ./secrets/aws_ses_password.txt
    db_logger_name:
      file: ./secrets/db_logger_name.txt
    db_logger_user:
      file: ./secrets/db_logger_user.txt
    db_logger_password:
      file: ./secrets/db_logger_password.txt
    db_logger_host:
      file: ./secrets/db_logger_host.txt
    db_logger_port:
      file: ./secrets/db_logger_port.txt
    django_secret_key:
      file: ./secrets/django_secret_key.txt
    django_superuser_name:
      file: ./secrets/django_superuser_name.txt
    django_superuser_email:
      file: ./secrets/django_superuser_email.txt
    django_superuser_password:
      file: ./secrets/django_superuser_password.txt
    redis_password:
      file: ./secrets/redis_password.txt
